version: '3'

services:
  download_artifacts:
    build:
      context: download_artifacts
      dockerfile: Dockerfile
    environment:
     - GITHUB_TOKEN
     - WORKFLOW_RUN_NUMBER
    volumes:
      - ../artifacts:/extractedArtifacts
  upload_dockerhub:
    build:
      context: upload_dockerhub
      dockerfile: Dockerfile
    privileged: true
    environment:
      - ELASTICSEARCH_DOCKER_PATH=/extractedArtifacts/DockerImages/elasticsearch.docker.tar.gz
      - WIKIBASE_BUNDLE_DOCKER_PATH=/extractedArtifacts/DockerImages/wikibase-bundle.docker.tar.gz
      - WIKIBASE_DOCKER_PATH=/extractedArtifacts/DockerImages/wikibase.docker.tar.gz
      - WDQS_DOCKER_PATH=/extractedArtifacts/DockerImages/wdqs.docker.tar.gz
      - WDQS_FRONTEND_DOCKER_PATH=/extractedArtifacts/DockerImages/wdqs-frontend.docker.tar.gz
      - QUICKSTATEMENTS_DOCKER_PATH=/extractedArtifacts/DockerImages/quickstatements.docker.tar.gz
      - WDQS_PROXY_DOCKER_PATH=/extractedArtifacts/DockerImages/wdqs-proxy.docker.tar.gz

      - WIKIBASE_SUITE_WDQS_IMAGE_URL
      - WIKIBASE_SUITE_WDQS_FRONTEND_IMAGE_URL
      - WIKIBASE_SUITE_WDQS_PROXY_IMAGE_URL
      - WIKIBASE_SUITE_QUICKSTATEMENTS_IMAGE_URL
      - WIKIBASE_SUITE_WIKIBASE_IMAGE_URL
      - WIKIBASE_SUITE_WIKIBASE_BUNDLE_IMAGE_URL
      - WIKIBASE_SUITE_ELASTICSEARCH_IMAGE_URL

      - WDQS_VERSION
      - MEDIAWIKI_VERSION
      - WMDE_RELEASE_VERSION
      - ELASTICSEARCH_VERSION
      - ELASTICSEARCH_PLUGIN_EXTRA_VERSION

      - DOCKER_HUB_REPOSITORY_NAME
      - DOCKER_HUB_ACCESS_TOKEN
      - DOCKER_HUB_ID
      - DRY_RUN
    volumes:
      - ../artifacts/${WORKFLOW_RUN_NUMBER}:/extractedArtifacts
  upload_tar:
    build:
      context: /upload_tar
      dockerfile: Dockerfile
    privileged: true
    environment:
     - RELEASE_HOST
     - RELEASE_USER
     - RELEASE_VERSION
     - RELEASE_MAJOR_VERSION
     - RELEASE_DIR
     - RELEASE_SSH_IDENTITY
     - WMDE_RELEASE_VERSION
     - DRY_RUN
    volumes:
      - ../artifacts/${WORKFLOW_RUN_NUMBER}:/extractedArtifacts
      - ${HOME}/.ssh/:/ssh-keys/:ro
