name: Linting

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint_dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          recursive: true

  lint_shell_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bewuethr/shellcheck-action@v2

  lint_selenium_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: variables.env
      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: npm-lint-cache
      - name: lint the selenium javascript tests
        run: |
          cd Docker/test/selenium 
          npm install
          npm run lint
  lint_diagrams:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: variables.env
      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: npm-lint-cache
      - name: lint the selenium javascript tests
        run: |
          cd diagrams
          npm install
          npm run lint
      - name: test building diagram
        run: |
          cd diagrams
          node make_overview.js
          